{
    'name': 'HRM Data Migration',
    'version': '17.0.0.1',
    'category': 'Human Resources',
    'summary': 'Module to import HR data from an external HRM system via API',
    'description': 'Custom module to import HR data from an external HRM system.',
    'author': 'Nikunj Dhameliya',
    'depends': ['base', 'hr', 'hr_holidays'],
    'data': [
        'data/data.xml',
        'data/ir_sequence.xml',
        'security/ir.model.access.csv',
        'views/process_import_export_view.xml',
        'views/hrms_hr_employee_view.xml',
        'views/hrms_hr_department_view.xml',
        'views/hrms_hr_leave_view.xml',
        'views/hr_data_dashboard_views.xml',
        'views/res_config_settings_views.xml',
        'views/common_log_book_view.xml',
        'views/common_log_lines_ept.xml',
        'views/hrms_hr_carrer_view.xml',
        'views/hrms_hr_contact_view.xml',
        'views/hr_employee_view.xml',
        'views/hr_department_view.xml',
        'views/hr_leave_view.xml',
        'views/hr_leave_detail_view.xml',
        'views/menu_items.xml'
    ],
    'cloc_exclude': ['**/*.xml', ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'AGPL-3'
}
